In [1]:
l = [223 , 333 , 5567, -9879]

In [2]:
l

[223, 333, 5567, -9879]

In [3]:
type(l)

list

In [4]:
import numpy as np

In [5]:
np.array(l)

array([  223,   333,  5567, -9879])

In [6]:
z= np.array(l)

In [7]:
z

array([  223,   333,  5567, -9879])

In [8]:
z= np.array [ 22 , True , 'sarah']

NameError: name 'true' is not defined

In [11]:
z= np.array ([ 22 , True , 'sarah'])

In [12]:
z

array(['22', 'True', 'sarah'], dtype='<U11')

In [13]:
print(z)

['22' 'True' 'sarah']


In [14]:
l

[223, 333, 5567, -9879]

In [17]:
l.count()

TypeError: list.count() takes exactly one argument (0 given)

In [18]:
l.pop()

-9879

In [19]:
l.reverse()

In [20]:
l

[5567, 333, 223]

In [23]:
l.insert(1 , 444)

In [24]:
l

[5567, 444, 333, 223]

In [27]:
c= np.array([  223,   333,  5567, -9879])

In [28]:
c

array([  223,   333,  5567, -9879])

In [29]:
c.mean()

-939.0

In [30]:
c.max()

5567

In [31]:
c.min()

-9879

In [33]:
l

[5567, 444, 333, 223]

In [34]:
l[:]

[5567, 444, 333, 223]

In [35]:
l[1:]

[444, 333, 223]

In [36]:
l[2:4]

[333, 223]

In [38]:
c

array([  223,   333,  5567, -9879])

In [39]:
c[2:4]

array([ 5567, -9879])

In [40]:
c[2:4] = 222

In [41]:
c

array([223, 333, 222, 222])

In [45]:
y = c.copy()

In [46]:
y

array([223, 333, 222, 222])

In [47]:
y [2:4] = 666

In [48]:
y

array([223, 333, 666, 666])

In [49]:
c

array([223, 333, 222, 222])

In [50]:
l

[5567, 444, 333, 223]

In [52]:
l[2:4] 

[333, 223]

In [54]:
l[2:4] = "444"

In [55]:
l

[5567, 444, '4', '4', '4']

In [56]:
l[0] = 33

In [57]:
l

[33, 444, '4', '4', '4']